DROP SCHEMA IF EXISTS common CASCADE; 

CREATE SCHEMA IF NOT EXISTS common; 

DROP SCHEMA IF EXISTS employee CASCADE; 

CREATE SCHEMA IF NOT EXISTS employee; 

DROP SCHEMA IF EXISTS company CASCADE; 

CREATE SCHEMA IF NOT EXISTS company; 

DROP SCHEMA IF EXISTS person CASCADE; 

CREATE SCHEMA IF NOT EXISTS person;

